// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrTtktqmPd_rgin2MU6JZ8JQpqnARzmRA',
    appId: '1:995000387672:web:a54f6120803e1dc69ca22d',
    messagingSenderId: '995000387672',
    projectId: 'group8-app-6aab4',
    authDomain: 'group8-app-6aab4.firebaseapp.com',
    storageBucket: 'group8-app-6aab4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzvB2qIo-q6_S36cQ1jkpsteUEiMgyjP0',
    appId: '1:995000387672:android:2e92d1e218f08a0e9ca22d',
    messagingSenderId: '995000387672',
    projectId: 'group8-app-6aab4',
    storageBucket: 'group8-app-6aab4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0oSOi_0stTCft84QbMFutHGY44ZrAi8',
    appId: '1:995000387672:ios:584f71b1132af2b49ca22d',
    messagingSenderId: '995000387672',
    projectId: 'group8-app-6aab4',
    storageBucket: 'group8-app-6aab4.appspot.com',
    iosBundleId: 'com.example.goup8App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa0oSOi_0stTCft84QbMFutHGY44ZrAi8',
    appId: '1:995000387672:ios:198e31df9acdec6b9ca22d',
    messagingSenderId: '995000387672',
    projectId: 'group8-app-6aab4',
    storageBucket: 'group8-app-6aab4.appspot.com',
    iosBundleId: 'com.example.goup8App.RunnerTests',
  );
}
